// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTLMw8jVncYqxOw0tWau4W1Z6m1vRD5n0',
    appId: '1:450844579980:web:4dc667ef748460845a03a9',
    messagingSenderId: '450844579980',
    projectId: 'authtutorial-36e97',
    authDomain: 'authtutorial-36e97.firebaseapp.com',
    storageBucket: 'authtutorial-36e97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7BgxAjg3nBnibmoxpfrNhRCwyHAWCx-8',
    appId: '1:450844579980:android:98e2d02fd81c628a5a03a9',
    messagingSenderId: '450844579980',
    projectId: 'authtutorial-36e97',
    storageBucket: 'authtutorial-36e97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyigK9INSTW-wMZ2rtcAEZRjVd5MD2ZAk',
    appId: '1:450844579980:ios:1bcd3079c585271f5a03a9',
    messagingSenderId: '450844579980',
    projectId: 'authtutorial-36e97',
    storageBucket: 'authtutorial-36e97.appspot.com',
    iosBundleId: 'com.example.modernUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyigK9INSTW-wMZ2rtcAEZRjVd5MD2ZAk',
    appId: '1:450844579980:ios:1bcd3079c585271f5a03a9',
    messagingSenderId: '450844579980',
    projectId: 'authtutorial-36e97',
    storageBucket: 'authtutorial-36e97.appspot.com',
    iosBundleId: 'com.example.modernUi',
  );
}
